WITH regimen_fiscal_preferencial AS (
    SELECT 'AF' AS country_code UNION ALL SELECT 'AO' UNION ALL SELECT 'AQ' UNION ALL SELECT 'DZ' UNION ALL
    SELECT 'BD' UNION ALL SELECT 'BY' UNION ALL SELECT 'BO' UNION ALL SELECT 'BQ' UNION ALL SELECT 'BI' UNION ALL
    SELECT 'BT' UNION ALL SELECT 'KH' UNION ALL SELECT 'TD' UNION ALL SELECT 'VA' UNION ALL SELECT 'KM' UNION ALL
    SELECT 'CG' UNION ALL SELECT 'KP' UNION ALL SELECT 'CI' UNION ALL SELECT 'CU' UNION ALL SELECT 'EG' UNION ALL
    SELECT 'ER' UNION ALL SELECT 'ET' UNION ALL SELECT 'FJ' UNION ALL SELECT 'GA' UNION ALL SELECT 'GM' UNION ALL
    SELECT 'GP' UNION ALL SELECT 'GU' UNION ALL SELECT 'GF' UNION ALL SELECT 'GN' UNION ALL SELECT 'GW' UNION ALL
    SELECT 'GQ' UNION ALL SELECT 'GY' UNION ALL SELECT 'HT' UNION ALL SELECT 'HN' UNION ALL SELECT 'IR' UNION ALL
    SELECT 'IQ' UNION ALL SELECT 'BV' UNION ALL SELECT 'CX' UNION ALL SELECT 'MF' UNION ALL SELECT 'GS' UNION ALL
    SELECT 'NF' UNION ALL SELECT 'PN' UNION ALL SELECT 'AX' UNION ALL SELECT 'CC' UNION ALL SELECT 'FK' UNION ALL
    SELECT 'HM' UNION ALL SELECT 'MP' UNION ALL SELECT 'UM' UNION ALL SELECT 'SB' UNION ALL SELECT 'SJ' UNION ALL
    SELECT 'VI' UNION ALL SELECT 'WF' UNION ALL SELECT 'KG' UNION ALL SELECT 'KI' UNION ALL SELECT 'LA' UNION ALL
    SELECT 'LS' UNION ALL SELECT 'LY' UNION ALL SELECT 'MG' UNION ALL SELECT 'MW' UNION ALL SELECT 'ML' UNION ALL
    SELECT 'MQ' UNION ALL SELECT 'YT' UNION ALL SELECT 'MZ' UNION ALL SELECT 'MM' UNION ALL SELECT 'NP' UNION ALL
    SELECT 'NI' UNION ALL SELECT 'NE' UNION ALL SELECT 'NC' UNION ALL SELECT 'PW' UNION ALL SELECT 'PS' UNION ALL
    SELECT 'PF' UNION ALL SELECT 'PR' UNION ALL SELECT 'CF' UNION ALL SELECT 'CD' UNION ALL SELECT 'RE' UNION ALL
    SELECT 'EH' UNION ALL SELECT 'AS' UNION ALL SELECT 'BL' UNION ALL SELECT 'PM' UNION ALL SELECT 'SH' UNION ALL
    SELECT 'ST' UNION ALL SELECT 'SL' UNION ALL SELECT 'SY' UNION ALL SELECT 'SO' UNION ALL SELECT 'LK' UNION ALL
    SELECT 'SD' UNION ALL SELECT 'SS' UNION ALL SELECT 'SR' UNION ALL SELECT 'TW' UNION ALL SELECT 'TZ' UNION ALL
    SELECT 'TJ' UNION ALL SELECT 'IO' UNION ALL SELECT 'TF' UNION ALL SELECT 'TL' UNION ALL SELECT 'TG' UNION ALL
    SELECT 'TK' UNION ALL SELECT 'TO' UNION ALL SELECT 'TT' UNION ALL SELECT 'TM' UNION ALL SELECT 'TV' UNION ALL
    SELECT 'UZ' UNION ALL SELECT 'VE' UNION ALL SELECT 'YE' UNION ALL SELECT 'DJ' UNION ALL SELECT 'ZM' UNION ALL
    SELECT 'ZW'
),

zonas_francas AS (
    SELECT 'IQUIQUE' AS zona UNION ALL
    SELECT 'ZOFRI' UNION ALL
    SELECT 'PUNTA ARENAS' UNION ALL
    SELECT 'ARICA' UNION ALL
    SELECT 'ALTO HOSPICIO' UNION ALL
    SELECT 'TOCOPILLA' UNION ALL
    SELECT 'BOGOTA' UNION ALL
    SELECT 'BOGOTÁ' UNION ALL
    SELECT 'MEDELLIN' UNION ALL
    SELECT 'MEDELLÍN' UNION ALL
    SELECT 'CALI' UNION ALL
    SELECT 'MONTEVIDEO' UNION ALL
    SELECT 'COLON' UNION ALL
    SELECT 'COLÓN' UNION ALL
    SELECT 'CIUDAD DE PANAMA' UNION ALL
    SELECT 'CIUDAD DE PANAMÁ' UNION ALL
    SELECT 'ALAJUELA' UNION ALL
    SELECT 'DUBAI' UNION ALL
    SELECT 'JEBEL ALI' UNION ALL
    SELECT 'SHENZHEN' UNION ALL
    SELECT 'SHANGHAI' UNION ALL
    SELECT 'SINGAPUR' UNION ALL
    SELECT 'SINGAPORE' UNION ALL
    SELECT 'HONG KONG' UNION ALL
    SELECT 'MIAMI' UNION ALL
    SELECT 'HOUSTON' UNION ALL
    SELECT 'ROTTERDAM' UNION ALL
    SELECT 'HAMBURGO'
),

base AS (
    SELECT
        t.*,

        UPPER(TRIM(t.beneficiary_country_code)) AS beneficiary_country_code_clean,

        UPPER(
            COALESCE(t.beneficiary_city, '') || ' ' ||
            COALESCE(t.beneficiary_state, '') || ' ' ||
            COALESCE(t.beneficiary_address, '') || ' ' ||
            COALESCE(t.beneficiary_country_name, '')
        ) AS beneficiary_location_text

    FROM "db_prod"."transaction"."transaction" AS t
    WHERE t.start_date >= DATEADD(day, -90, CURRENT_DATE)
      AND UPPER(t.tx_status) = 'TRANSFERENCIA_EXITOSA'
)

SELECT
    b.transaction_id,
    b.customer_id,
    b.customer_email,
    b.remitter_account_type,
    b.start_date,
    b.origin_country,
    b.origin_currency,
    b.beneficiary_country_code,
    b.beneficiary_country_name,
    b.beneficiary_city,
    b.beneficiary_state,
    b.beneficiary_address,
    b.destiny_currency,
    b.destiny_amount_usd,
    b.beneficiary_id,
    b.beneficiary_name,

    CASE
        WHEN rfp.country_code IS NOT NULL THEN 'REGIMEN_FISCAL_PREFERENCIAL'
        WHEN zf.zona IS NOT NULL THEN 'ZONA_FRANCA'
    END AS etiqueta_riesgo,

    zf.zona AS zona_franca_match

FROM base AS b

LEFT JOIN regimen_fiscal_preferencial AS rfp
    ON b.beneficiary_country_code_clean = rfp.country_code

LEFT JOIN zonas_francas AS zf
    ON b.beneficiary_location_text LIKE '%' || zf.zona || '%'

WHERE rfp.country_code IS NOT NULL
   OR zf.zona IS NOT NULL

ORDER BY
    b.destiny_amount_usd DESC,
    b.start_date DESC;
